mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns =[
    #path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/',include('blog.urls', namespace='blog')),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


# Create your models here.
class Post(models.Model):
    STATUS_CHOICE = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)

    # A slug field in Django is used to store and generate valid URLs for
    # your dynamically created web pages.
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    objects = models.Manager()  # the default manager
    published = PublishedManager()  # our customer manager

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

mysite/blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
# Create your views here.
# def post_list(request):
#     posts = Post.published.all()
#     return render(request, 'blog/post/list.html' ,{'posts': posts},)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method =='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/details.html', {'post': post,
                                                      'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

'''
    Handles the email forma and sends an email when its successfully submittted
'''
def post_share(request, post_id):
     # Retrieve post byt id
    post = get_object_or_404(Post, id=post_id, status ='published')
    # use the below line if you use your SMTP server for sending emails

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed  validation, then you use the below form.cleaned_data to access the form data.
            cd = form.cleaned_data
            # use the below code if you choose to setup your own SMTP server
            # post_url = request.build_absolute_uri(post.get_absolute_url())
            # subject = f'{cd.name} recommends you read {post.title}'
            # message = f'Read {post.title} at {post_url}\n\n {cd.name}\'s comments: {cd.comments}'
            # send_mail (subject, message, 'admin@myblog.com', cd.to)
            # sent = True
            # send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{'post':post, 'form': form})
#   this is for your own SMTP server
#   return render(request, 'blog/post/share.html',{'post':post, 'form': form}, 'sent':sent)

mysite/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
<div id="sidebar">
  <h2>My Blog</h2>
  <p>This is my blog.</p>
</div>
</body>
</html>

mysite/blog/templates/blog/post/details.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post.</a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment {{ total_comments|pluralize }}
        </h2>
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
                </p>
            {{ comment.body|linebreaks }}
            </div>
            {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
        {% else %}
            <h2>Add a new comment</h2>
            <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
    {% endwith %}
{% endblock %}

mysite/blog/templates/blog/post/list.html
{% extends 'base.html' %}
{% block title %}My Blog{% endblock  %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <p class="date">
            Published {{post.publish}} by {{post.author}}
        </p>
        {{post.body|truncatewords:30|linebreaks}}
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock  %}

mysite/blog/templates/blog/post/share.html
{% extends 'base.html' %}
{% block title %}Share a post{% endblock  %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent.</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-email</h1>
        <form method="post">
            {{ form.as_p }}
{# of you can use iterating through form like below #}
{#   {% for fields in form %} <div> {{ fields.errors }}{{ fields.label_tag }} {{ field }}</div>  #}
        {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock  %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

    <span class="current">
        Page{{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
      </span>
</div>